Repository Osekai/osekai, pull requests merged in 2022-12, with the labels that each got.

#71 Add new languages as experimental
  global/php/osekaiLocalization.php
Labels: size/S

#72 Stop redirecting to https when on localhost
  .htaccess
Labels: size/XS

#73 Hopefully make admin stay on latest commit always
  .gitmodules
Labels: size/XS

#74 Use new translators user shows
  global/php/functions.php
  misc/translators/index.php
Labels: size/M

#76 Finnish is no longer WIP
  global/php/osekaiLocalization.php
Labels: size/XS, Code

#77 Mobile update dec2022
  .htaccess
  global/css/main.css
  home/css/main.css
  home/img/medalhunters-bg.png
  home/img/medalhunters-bg.svg
  home/img/medalhunters-logo.png
  home/img/medalhunters.svg
  home/index.php
  medals/css/main.css
Labels: size/L

#83 Don't do an extra SQL to check if user is in db
  medals/api/extrainfo.php
  misc/translators/index.php
Labels: size/XS

#82 Refactor medal lock check a little bit
  medals/api/beatmaps.php
  medals/js/functions.js
Labels: size/S

#81 Put tippy text in medal img and change hover state
  medals/js/functions.js
Labels: Enhancement, Medals, size/XS, Code

#78 New general design across all sites
  global/css/main.css
  global/php/functions.php
  profiles/css/main.css
  profiles/index.php
  template.sql
Labels: Enhancement, Medals, Profiles, Rankings, Reasonably Important, Design, size/L

#85 Fix `Snowflakes`
  global/css/main.css
  global/php/navbar.php
Labels: Enhancement, size/S, Code, Design

#86 Order groups properly on profiles and team page
  global/js/main.js
  global/php/functions.php
  home/team.php
  profiles/js/functions.js
Labels: Enhancement, Reasonably Important, Code, Design, size/M

#97 New `Groups` Page (`Misc/Groups`)
  global/css/main.css
  global/php/functions.php
  misc/css/main.css
  misc/groups/api/api.php
  misc/groups/css/main.css
  misc/groups/index.php
  misc/groups/js/functions.js
  misc/translators/index.php
  profiles/groups.php
Labels: Enhancement, Code, Design, size/XL, Frontend, Backend

#98 Use relative path on other apps dropdown
  global/php/navbar.php
Labels: size/XS

#101 Fix undefined names on group page
  misc/groups/js/functions.js
Labels: size/XS

#80 Add base docker support
  .dockerignore
  Dockerfile
  db/1.template.sql
  db/2.snippet.badges.sql
  db/3.snippet.rankings.sql
  db/4.snippet.snapshots_versions.sql
  docker-compose.yml
  docker/docker_run.sh
  docker/error_reporting.ini
  docker/xdebug.ini
Labels: Enhancement, Reasonably Important, Code, size/L

#102 Fix lang files
  .gitignore
  global/lang/en_GB/misc/global.json
  global/lang/en_GB/misc/groups.json
  global/lang/en_GB/misc/translators.json
Labels: size/S

#103 Fix typo in translators page
  global/lang/en_GB/misc/translators.json
Labels: size/XS

#104 Update translators to id 0 when restricted
  misc/translators/index.php
Labels: size/S

#105 bruh
  misc/translators/index.php
Labels: size/XS

#106 Fix regression: localization module being loaded outside of frontend
  global/php/functions.php
Labels: size/XS

#107 Fix Osekai Scripts... Oops.
  rankings/api/upload/scripts-rust/up_ranking.php
Labels: size/XS

#108 Fix loading localization too late
  global/php/functions.php
Labels: size/L

#109 Add @jiniux to team page
  home/index.php
Labels: size/XS

#112 Make groups show up in allmode in profiles
  global/php/osu_api_functions.php
Labels: size/M

#111 Fix string issues in Osekai Badges
  badges/js/functions.js
Labels: size/XS

#113 Limit role amount in comments to stop overflows
  db/1.template.sql
  global/css/comments.css
  global/css/main.css
  global/js/comment_system.js
  global/js/main.js
Labels: Enhancement, Reasonably Important, Code, Design, size/L, Frontend, Backend

#110 Refactor(?) comment system apis
  global/api/comment_system.php
Labels: Reasonably Important, Code, size/L, Backend

#115 Final fix on the comments... I hope
  global/api/comment_system.php
Labels: Bug, Enhancement, size/XS, Reasonably Important, Code, Design, Frontend, Backend

#116 I hate life
  global/api/comment_system.php
Labels: Enhancement, size/XS, Reasonably Important, Code, Design, Frontend, Backend

#117 Fix typo in comments system
  global/api/comment_system.php
Labels: size/XS

#118 Fix typo part 2
  global/api/comment_system.php
Labels: size/XS

#119 oseaki is no more :crab:
  badges/css/main.css
  global/css/experimental.css
  global/css/main.css
  global/css/main.min.css
  global/php/functions.php
  global/php/navbar.php
  index.php
Labels: Enhancement, size/S, Code, Backend

#122 Notification system v2
  global/api/notification_system.php
  global/js/main.js
  global/js/navbar.js
  global/js/xhr.js
  global/php/navbar.php
Labels: Enhancement, Reasonably Important, Code, Design, size/L, Frontend, Backend

#124 Add generic favicon.ico file
  favicon.ico
Labels: size/XS

#126 Language support update 2022
  global/php/osekaiLocalization.php
Labels: Enhancement, size/XS, Code, Backend

#128 oops
  global/php/osekaiLocalization.php
Labels: size/XS

#129 Implement new Profiles cover design
  global/css/main.css
  home/css/main.css
  home/team.php
  misc/groups/css/main.css
  misc/groups/js/functions.js
  profiles/css/main.css
  profiles/index.php
  profiles/js/functions.js
Labels: Enhancement, Profiles, Reasonably Important, Code, Design, size/XL, Frontend, Backend

#132 Delete Zebra_Session.php
  global/php/Zebra_Session.php
Labels: Code, size/XL, Backend

#136 Make banner url host dynamic and fix it
  profiles/js/functions.js
Labels: Enhancement, Profiles, size/XS, Reasonably Important, Code, Frontend, Backend

#134 Refactor goals.php
  global/php/api_controller.php
  global/php/exceptions.php
  global/php/functions.php
  global/php/osekaiDB.php
  global/php/repositories/goals_repository.php
  global/php/services/goals_service.php
  global/php/utils.php
  profiles/api/goals.php
Labels: Enhancement, Code, size/L, Backend

#137 Add rel="me" for Mastodon socials on Team page
  home/team.php
Labels: Enhancement, size/XS, Code, Backend

#139 Proposal of fixs all over the website
  global/lang/en_GB/comments.json
  global/lang/en_GB/contact.json
  global/lang/en_GB/donate.json
  global/lang/en_GB/faq.json
  global/lang/en_GB/home.json
  global/lang/en_GB/profiles.json
Labels: Enhancement, Code, size/M, Backend

#140 Update role in `The Team` list on `Home` page
  global/lang/en_GB/home.json
Labels: Enhancement, size/XS, Code, Backend

#138 Auto-redirect when using username in `user` field
  profiles/index.php
Labels: Enhancement, size/XS, Code, Backend

#142 Refactor most_visited_overall.php following the pattern used in goals.php
  global/php/functions.php
  global/php/repositories/profiles_visited_repository.php
  profiles/api/most_visited_overall.php
  profiles/js/functions.js
Labels: size/M

#143 Don't get notifications if function is undefined
  global/js/xhr.js
Labels: Enhancement, size/XS, Code, Backend

#145 Refactor recent_visits.php. Added a base limit of 5 results.
  global/php/repositories/profiles_visited_repository.php
  profiles/api/recent_visits.php
  profiles/js/functions.js
Labels: Enhancement, Profiles, Code, size/M, Backend, Very Important

#149 Refactor most_visited.php
  global/php/api_controller.php
  global/php/osekaiDB.php
  global/php/repositories/profiles_visited_repository.php
  profiles/api/most_visited.php
  profiles/api/most_visited_overall.php
Labels: Enhancement, Profiles, Code, size/L, Backend

#150 Refactor medals search and filters
  global/js/main.js
  global/php/functions.php
  medals/api/filters.php
  medals/api/medals.php
  medals/js/functions.js
Labels: Enhancement, Medals, Code, Design, size/L, Frontend, Backend

#152 Make text strings on user group page localizable
  global/js/localization.js
  global/lang/en_GB/groups.json
  global/php/osekaiLocalization.php
  misc/groups/js/functions.js
Labels: size/S

#153 Add all `Groups` names and descriptions
  global/lang/en_GB/groups.json
Labels: Enhancement, size/S, Reasonably Important, Code, Frontend, Backend, changelog:Addition

#154 Remove all traces of `Osekai Horse Betting` app
  README.md
Labels: Enhancement, size/XS, Code, Design, Frontend, Backend, Very Important, changelog:Removal

#155 Translate SqlTimeSpecifierUnit into costants to support older versions
  global/php/osekaiDB.php
  profiles/api/most_visited.php
Labels: size/M

#156 Localize text in group list
  misc/groups/js/functions.js
Labels: size/XS

#159 Update OsekaiSessions and GlobalCache structure
  db/1.template.sql
Labels: Enhancement, size/S, Reasonably Important, Code, Backend, changelog:Change

#158 Add changelog API.
  config.php.example
  docker/docker_run.sh
  global/php/api_controller.php
  global/php/functions.php
  global/php/osekaiDB.php
  global/php/osekaiHttpRequest.php
  global/php/repositories/changelog_entry_repository.php
  global/php/repositories/changelog_repository.php
  global/php/services/changelog_service.php
  misc/changelog/api/changelog.php
  misc/changelog/api/changelog_update.php
  misc/changelog/api/github_labels_proxy.php
Labels: Enhancement, Reasonably Important, Code, size/L, Backend

#161 Implement Lightweight theme
  global/css/lightweight.css
  global/js/main.js
  home/css/lightweight.css
  medals/css/lightweight.css
  profiles/css/lightweight.css
Labels: Enhancement, Code, Design, size/L, Frontend, Backend, changelog:Addition

#162 Fix groups dropdown being overlapped by beatmaps
  global/css/main.css
Labels: Enhancement, Medals, size/XS, Reasonably Important, Code, Design, Frontend, Backend, changelog:Change

#163 Enable `User Groups` link in navbar
  global/php/navbar.php
Labels: Enhancement, size/XS, Code, Frontend, Backend, changelog:Change

#164 Make `groups` clickable
  global/js/main.js
  global/php/functions.php
Labels: Enhancement, size/XS, Code, Frontend, Backend, changelog:Change

#165 Revert "Make `groups` clickable"
  global/js/main.js
  global/php/functions.php
Labels: size/XS

#166 Add new font for large bodies of text
  global/css/comments.css
  global/css/main.css
  global/php/functions.php
  medals/css/main.css
  misc/groups/css/main.css
Labels: Enhancement, size/S, Reasonably Important, Code, Design, Frontend, Backend, changelog:Change

#167 Finalize other apps
  global/css/lightweight.css
  global/php/navbar.php
  misc/css/main.css
  misc/groups/css/light.css
  misc/groups/css/main.css
  misc/groups/index.php
  misc/groups/js/functions.js
  misc/php/main.php
  misc/translators/css/light.css
  misc/translators/css/main.css
  misc/translators/index.php
Labels: Enhancement, Reasonably Important, Code, Design, size/L, Frontend, Backend, changelog:Addition

#169 Make `groups` clickable... AGAIN
  global/js/main.js
  global/php/functions.php
Labels: Enhancement, size/XS, Code, Backend, changelog:Change

#168 Fix medals not working when logged out
  medals/api/filters.php
Labels: Enhancement, size/XS, Reasonably Important, Code, Frontend, Backend, changelog:Change

#170 The opening of a new era
  legal/contact.php
Labels: size/XS

#172 Fix link in `TEAM LEAD` description
  global/lang/en_GB/groups.json
Labels: Enhancement, size/XS, Code, Backend, changelog:Change

#171 Fix groups page and add mobile support
  global/css/main.css
  global/js/main.js
  global/php/functions.php
  misc/groups/css/main.css
Labels: Enhancement, Reasonably Important, Code, Design, size/M, Frontend, Backend, changelog:Change

#173 Make thin variants on other languages more readable
  global/php/osekaiLocalization.php
Labels: size/XS

#176 Visible links
  global/css/comments.css
  global/css/main.css
  global/fonts/osekai-icon-font/style.css
  home/css/main.css
  misc/groups/css/main.css
  misc/groups/js/functions.js
  misc/translators/index.php
Labels: size/M

#177 Add StatsPageViewsRepository and StatsPageViewsService.
  global/php/functions.php
  global/php/osekaiDB.php
  global/php/repositories/stats_page_views_repository.php
  global/php/services/stats_page_views_service.php
  global/php/utils.php
Labels: size/L

#175 Add licence and third party licences to the site
  global/php/functions.php
  global/php/navbar.php
  legal/licences.php
Labels: size/L

#178 Dont use absolute paths for navbar elements
  global/php/navbar.php
Labels: size/S

#179 Improve handling of filtering medals for not logged in users
  medals/api/filters.php
  medals/js/functions.js
Labels: size/XS

#180 Fix Traditional Chinese english name
  global/php/osekaiLocalization.php
Labels: size/XS

#181 Fix Licence link in navbar dropdown
  global/php/navbar.php
Labels: size/XS

#182 Inprove search bar design on medals
  medals/css/main.css
Labels: size/XS

#183 Fix few remaining issues with new link highlighting
  global/css/light.css
  global/css/main.css
  global/js/comment_system.js
  profiles/index.php
Labels: size/S

#184 Implement new divisor design for medal listing
  medals/js/functions.js
Labels: size/M

#187 Make medal groups collapsable
  medals/js/functions.js
Labels: size/S

#186 Always have snowflakes (but off by default outside of christmas time)
  global/js/main.js
  global/php/navbar.php
Labels: size/L

#194 Add english name tooltip to locales in Language dropdowN
  global/php/navbar.php
Labels: size/XS

#195 Use pointer cursor when hovering on dropdown items
  global/css/main.css
Labels: size/XS

#196 More localization!
  global/css/main.css
  global/js/localization.js
  global/js/main.js
  global/lang/en_GB/medals.json
  global/lang/en_GB/navbar.json
  global/lang/en_GB/profiles.json
  global/php/navbar.php
  global/php/osekaiLocalization.php
  medals/js/functions.js
  profiles/js/functions.js
Labels: Enhancement, Code, size/L, Frontend, Backend, changelog:Change

#193 Enable bulgarian
  global/php/osekaiLocalization.php
Labels: size/XS

#197 Capitalize bulgarian name
  global/php/osekaiLocalization.php
Labels: size/XS

#199 Auto select search input when opening search
  global/js/search.js
Labels: size/XS

#200 Add missing nolink class to translators cards
  misc/translators/index.php
Labels: size/XS

#203 Update socials order in Osekai team list
  home/index.php
Labels: Enhancement, size/S, Code, Frontend, Backend, changelog:Change

#201 Add "Restricted" row to ranking
  db/1.template.sql
  rankings/api/upload/scripts-rust/up_ranking.php
Labels: size/XS, Reasonably Important

#204 Prevent overflow of donation percentage bar.
  donate/index.php
Labels: size/XS

#205 profiles/goals: Fix dates being wrong because of timezone
  profiles/js/functions.js
Labels: size/S

#206 Implement new settings UI
  global/css/light.css
  global/css/main.css
  global/js/dropdown_system.js
  global/js/main.js
  global/js/navbar.js
  global/php/navbar.php
  medals/js/functions.js
Labels: Enhancement, size/XXL, Reasonably Important, Code, Design, Frontend, Backend, changelog:Change

#207 gitinfo: Refactor the thing
  global/css/main.css
  global/php/functionsEnd.php
  global/php/gitInfo.php
Labels: size/M

#210 Allow CORS on fonts
  .htaccess
Labels: size/XS

#212 Fix Show Medals From All Modes option
  global/js/osu_api.js
Labels: size/XS
