Repository Osekai/osekai, pull requests merged in 2022-11, with the labels that each got.

#14 snapshots: Fix null reference when there arent ANY snapshot in db
  global/php/osekaiDB.php
  profiles/api/snapshots_integration.php
Labels: size/XS

#16 Fix completion bar colors not updating when switching profiles
  profiles/js/functions.js
Labels: Profiles, size/XS

#21 timeline: Fix dots being marked as active when they shouldn't
  profiles/js/functions.js
Labels: size/S

#23 Auto-enable experimental and dev tools when running in dev mode
  global/php/functions.php
Labels: size/XS

#12 profiles: Default to standard when mode is not set
  profiles/js/functions.js
Labels: Profiles, size/S, Code

#25 release change to main oops
  .htaccess
Labels: size/XS

#26 Show git info in `Debug` menu
  global/php/functionsEnd.php
Labels: size/S

#27 Fix comments being able to go long boi
  global/css/comments.css
Labels: size/XS

#28 Make git info clickable and UTC
  global/php/functionsEnd.php
Labels: size/XS

#29 fix accidental echo
  global/php/functionsEnd.php
Labels: size/XS

#30 it's licence time
  LICENCE
Labels: size/S

#32 Crowdin update 1
  .gitignore
  config.php.example
  global/crowdin.yml
  global/lang/updateLang.php
  global/note.txt
Labels: size/M

#33 First pass of strings for now
  global/lang/en_GB/general.json
  global/lang/en_GB/home.json
  global/lang/en_GB/medals.json
  global/lang/en_GB/navbar.json
  global/lang/en_GB/profiles.json
  global/php/navbar.php
  home/index.php
  medals/index.php
  medals/js/functions.js
  profiles/index.php
  profiles/js/functions.js
Labels: size/L

#36 Add MegaMix_Craft's second nickname
  home/index.php
Labels: Enhancement, size/XS, Code, Design

#38 Fix "loo k" typo
  global/lang/en_GB/report.json
Labels: size/XS

#40 Add new logo animation to home page
  global/php/functions.php
  home/css/light.css
  home/css/main.css
  home/img/osekai-logo.json
  home/index.php
  home/js/main.js
Labels: Enhancement, Design, size/M

#41 Don't reply to exp requests when not logged in
  expon.php
  global/api/expoff.php
Labels: size/XS

#46 Add new groups system to comments
  global/api/comment_system.php
  global/css/comments.css
  global/css/main.css
  global/js/comment_system.js
  global/js/main.js
  global/php/functions.php
  template.sql
Labels: size/L

#49 Use new profile badges on profiles
  global/css/main.css
  global/js/main.js
  global/php/osu_api_functions.php
  profiles/css/main.css
  profiles/js/functions.js
Labels: size/XXL

#48 Add vscode to .gitignore
  .gitignore
Labels: size/XS

#50 Fix error
  global/js/main.js
Labels: size/XS

#51 Finally fix roles on comments
  global/api/comment_system.php
Labels: size/S

#52 Add new team page
  global/css/main.css
  global/fonts/osekai-icon-font/fonts/Osekai-Icon-Font.svg
  global/fonts/osekai-icon-font/fonts/Osekai-Icon-Font.ttf
  global/fonts/osekai-icon-font/fonts/Osekai-Icon-Font.woff
  global/fonts/osekai-icon-font/selection.json
  global/fonts/osekai-icon-font/style.css
  global/lang/en_GB/home.json
  global/php/functions.php
  home/css/light.css
  home/css/main.css
  home/index.php
  home/team.php
Labels: Enhancement, size/XL

#54 Make translators page use osu! Username instead of Crowdin username
  misc/translators/index.php
Labels: size/XS

#56 Update badge design & fix local server rewrite
  global/css/main.css
  global/php/functions.php
Labels: Bug, Design, size/M

#55 Fix "Mild overlap issue" (#42)
  global/css/main.css
Labels: Enhancement, Rankings, size/XS, Design

#53 Change home panel img border radius to 16px
  home/css/main.css
Labels: Enhancement, size/XS, Reasonably Important, Code, Design

#57 Use hash instead of arbitrary value for OSEKAI_VERSION
  config.php.example
  global/php/functions.php
  global/php/functionsEnd.php
  global/php/gitInfo.php
Labels: size/S

#58 Remove newline from version hash
  global/php/functions.php
Labels: size/XS

#63 Use isExperimental for apps dropdown and fix role runtime error
  global/php/functions.php
  global/php/navbar.php
Labels: size/XS

#66 Update socials in `The Team` list
  home/index.php
Labels: Enhancement, size/XS, Code

#65 Don't make use of absolute paths anymore
  404/index.php
  authenticator/auth.php
  config.php.example
  donate/index.php
  global/php/functions.php
  global/php/login.php
  global/php/logout.php
  global/php/navbar.php
  global/php/osekaiAnalytics.php
  global/php/search_overlay.php
  home/index.php
  index.php
  legal/contact.php
  legal/privacy.php
  medals/dev.php
  medals/index.php
  medals/js/functions.js
  medals/new_ui.php
  misc/translators/index.php
  omh/retro_achiever/index.php
  rankings/index.php
  snapshots/api/overall_views.php
  snapshots/index.php
  snapshots/js/functions.js
  snapshots/legacy.php
  tools/index.php
  tools/tool.php
Labels: Enhancement, Reasonably Important, Code, size/L

#67 Improve readability on settings panel
  global/css/main.css
Labels: Enhancement, size/XS, Code, Design

#70 fix missing comma on home page
  home/index.php
Labels: size/XS
