Repository Osekai/osekai, pull requests merged in 2023-08, with the labels that each got.

#336 Update homepage
  global/js/graphics/mesh_gradient.js
  home/css/light.css
  home/css/main.css
  home/css/themes/flat-light.css
  home/css/themes/lightweight.css
  home/img/background.png
  home/img/badges.png
  home/img/faq-bg.png
  home/img/faqs/snapshots_files.png
  home/img/medalhunters-bg.png
  home/img/medalhunters-logo.png
  home/img/medals.png
  home/img/newmedals.png
  home/img/oss-bg.jpg
  home/img/profiles.png
  home/img/rankings.png
  home/img/snapshots.png
  home/index.php
  home/js/background.js
  home/js/main.js
Labels: size/XL

#339 solutiontracker db
  db/1.template.sql
Labels: size/XL

#341 Fix issues related to docker-compose services
  .dockerignore
  .gitignore
  docker-compose.yml
Labels: size/S

#345 update languages
  global/php/osekaiLocalization.php
Labels: Code, size/M, Backend, changelog:Addition

#344 Add new alert variant
  db/1.template.sql
  global/css/main.css
  global/js/main.js
  global/php/navbar.php
Labels: size/M

#343 Solution Tracker API - Add and get solutions and attempts. Remove scripts-rust legacy endpoints
  global/php/api_controller.php
  global/php/json_validator.php
  medals/api/favourite.php
  medals/solutionhunter/api/add_solution_attempt.php
  medals/solutionhunter/api/add_solution_idea.php
  medals/solutionhunter/api/common.php
  medals/solutionhunter/api/get_solution_attempts.php
  medals/solutionhunter/api/get_solution_ideas.php
  medals/solutionhunter/php/models.php
  medals/solutionhunter/php/services.php
  rankings/api/upload/scripts-rust/base_api.php
  rankings/api/upload/scripts-rust/down_badges.php
  rankings/api/upload/scripts-rust/down_badges_extra.php
  rankings/api/upload/scripts-rust/down_medals.php
  rankings/api/upload/scripts-rust/down_members.php
  rankings/api/upload/scripts-rust/down_ranking_ids.php
  rankings/api/upload/scripts-rust/down_rarity.php
  rankings/api/upload/scripts-rust/finish.php
  rankings/api/upload/scripts-rust/progression.php
  rankings/api/upload/scripts-rust/up_badges.php
  rankings/api/upload/scripts-rust/up_medals.php
  rankings/api/upload/scripts-rust/up_medals_rarity.php
  rankings/api/upload/scripts-rust/up_ranking.php
Labels: Enhancement, Code, size/XL, Backend, changelog:Addition

#348 default to home
  profiles/index.php
Labels: size/XS

#350 fix teams router
  .htaccess
  teams/js/routing.js
  teams/templates/tabbed_page.php
  teams/views/load_view.php
Labels: size/M

#351 Teams UI 4
  global/php/functions.php
  teams/css/main.css
  teams/js/functions.js
  teams/js/home/dashboard.js
  teams/js/routing.js
  teams/router.php
  teams/templates/tabbed_page.php
  teams/views/home/dashboard.php
  teams/views/load_view.php
Labels: size/M
