Repository Osekai/osekai, pull requests merged in 2023-04, with the labels that each got.

#280 Fix medals
  medals/js/functions.js
Labels: size/XS

#281 Fix comments
  global/js/main.js
Labels: size/XS

#282 `>:(`
  global/lang/en_GB/contact.json
  global/php/navbar.php
Labels: size/S, Code, Frontend, Backend, changelog:Change

#283 Nya~
  404/index.php
Labels: Enhancement, size/S, Code, Frontend, Backend, changelog:Change

#285 Add dark reader lock
  global/php/functions.php
Labels: size/XS
