Repository Osekai/osekai, pull requests merged in 2023-06, with the labels that each got.

#301 Fix overflowing text on taller screens (16:10)
  medals/css/main.css
Labels: size/XS

#302 add hush hush expert
  global/css/main.css
  global/php/osu_api_functions.php
  profiles/js/functions.js
Labels: size/S

#304 Update The Team... again, lol
  global/lang/en_GB/home.json
  home/api/team.php
Labels: size/S, Code, Frontend, Backend, changelog:Change

#303 Fix new groupings
  api/profiles/get_user.php
  global/css/main.css
  global/js/variables.js
  global/php/navbar.php
  global/php/osu_api_functions.php
  medals/api/filters.php
  medals/api/medals.php
  medals/js/functions.js
  profiles/index.php
  profiles/js/functions.js
Labels: size/L

#306 fix osekai
  global/php/osekaiAnalytics.php
Labels: size/S

#308 fix level formula
  global/php/utils.php
Labels: size/XS

#312 Fix Discord social spacing?
  profiles/js/functions.js
Labels: Enhancement, Profiles, size/XS, Code, Frontend, Backend, changelog:Change

#313 nyA
  profiles/js/functions.js
Labels: size/XS
