Repository Osekai/osekai, pull requests merged in 2023-02, with the labels that each got.

#246 Change rankings limit from 1k to 2.5k
  rankings/api/api.php
Labels: size/S

#247 fix width
  rankings/js/functions.js
Labels: size/S

#248 Move snowflakes to JS
  global/css/main.css
  global/js/main.js
  global/php/navbar.php
Labels: size/L

#250 Make medals_nogrouping endpoint return JSON content type
  medals/api/medals_nogrouping.php
Labels: size/XS

#251 Update mastodon links
  global/php/navbar.php
  home/index.php
Labels: size/XS

#252 Remove invalid image url in main.css
  global/css/main.css
Labels: size/XS

#253 Fix scrolling after closing app dropdown
  global/js/navbar.js
Labels: size/XS

#254 Fonts thingie
  global/php/functions.php
Labels: size/XS

#257 Add isset check to locale cookie getter
  global/php/osekaiLocalization.php
Labels: size/XS

#256 Delete use of undefined experimentals function
  global/php/navbar.php
Labels: size/XS

#255 Load team page through JS
  home/api/team.php
  home/css/main.css
  home/index.php
  home/js/main.js
  home/team.php
Labels: size/XL
