Repository Osekai/osekai, pull requests merged in 2023-03, with the labels that each got.

#263 Reafctor badges frontend
  badges/api/getBadges.php
  badges/api/getUsers.php
  badges/js/functions.js
Labels: size/L

#264 Fix badges name class
  badges/js/functions.js
Labels: size/XS

#265 Wipe badges when new uploaded
  rankings/api/upload/scripts-rust/up_badges.php
Labels: size/XS

#266 Refactor most of badges again
  badges/index.php
  badges/js/functions.js
Labels: size/L

#267 Lazy loading for badge pngs
  badges/css/main.css
  badges/index.php
  badges/js/functions.js
  global/css/main.css
  global/js/variables.js
  global/php/functions.php
Labels: size/XL

#268 Fix default badge not showing when img fails 1x
  badges/js/functions.js
Labels: size/S

#269 Fix warning when setting cookie when echo was already used
  global/php/functions.php
Labels: size/XS

#271 medals: Scroll to top when changing medals
  medals/js/functions.js
Labels: size/XS

#273 profiles: Add SPP
  global/php/osu_api_functions.php
  profiles/js/functions.js
Labels: size/M

#272 profiles: Preload user pfp when loading user
  profiles/js/functions.js
Labels: size/XS

#270 azelia: Add archiver count per year
  azelia/js/functions.js
Labels: size/S

#274 Homepage Update
  global/lang/en_GB/home.json
  home/img/oss-bg.jpg
  home/img/oss-icon.svg
  home/index.php
Labels: size/S

#275 Masive localization update
  badges/js/functions.js
  global/js/main.js
  global/js/navbar.js
  global/lang/en_GB/badges.json
  global/lang/en_GB/home.json
  global/lang/en_GB/navbar.json
  home/js/main.js
Labels: size/L

#276 Oseaki
  404/index.php
  authenticator/auth.php
  badges/index.php
  donate/index.php
  global/js/localization.js
  global/js/navbar.js
  global/php/navbar.php
  global/php/osekaiLocalization.php
  global/php/search_overlay.php
  home/img/osekai-logo.json
  home/index.php
  home/js/main.js
  index.php
  legal/contact.php
  legal/licences.php
  legal/privacy.php
  medals/index.php
  misc/changelog/index.php
  misc/php/main.php
  profiles/index.php
  profiles/js/functions.js
  rankings/index.php
  snapshots/index.php
  snapshots/js/functions.js
  snapshots/splash.txt
  tools/index.php
  tools/tool.php
Labels: size/XL

#277 Oseaki fix
  global/js/localization.js
  global/php/osekaiDB.php
  home/img/osekai.svg
  home/index.php
Labels: size/M

#278 Oseaki fix 3
  global/php/functions.php
  global/php/functionsEnd.php
  home/js/main.js
  medals/js/functions.js
  rankings/index.php
  rankings/js/functions.js
  snapshots/index.php
Labels: size/M

#279 use version on localization
  global/php/osekaiLocalization.php
Labels: size/XS
