Repository Osekai/osekai, pull requests merged in 2023-01, with the labels that each got.

#213 Only Report PHP Errors to Web UI
  api/setLanguage.php
  authenticator/api/create_user.php
  azelia/database/legacymigration.php
  docker/error_reporting.ini
  global/api/search.php
  global/api/sitemap.php
  global/php/functions.php
  global/php/osekaiSessionManager.php
  home/api/faq.php
  home/testLocalization.php
  medals/api/get_beatmap_pack_count.php
  misc/translators/index.php
  profiles/api/banner/save.php
  profiles/api/snapshots_integration.php
  rankings/api/api.php
  rankings/api/upload/scripts-rust/up_badges.php
  rankings/api/upload/scripts-rust/up_medals.php
  rankings/api/upload/scripts-rust/up_medals_rarity.php
  rankings/api/upload/scripts-rust/up_ranking.php
  snapshots/api/admin_deletescreenshot.php
  snapshots/api/admin_uploadscreenshot.php
  snapshots/api/announce_version.php
  snapshots/api/api.php
  snapshots/api/edit.php
  snapshots/api/upload.php
  snapshots/update_db.php
Labels: size/M

#217 remove loads of unused stuff
  global/css/experimental.css
  global/css/light.css
  global/css/main.css
  global/css/main.min.css
  global/doc/bmp2.xml
  global/img/branding/convert.py
  global/img/branding/raster/favi_unused/medals.png
  global/img/branding/raster/favi_unused/polls.png
  global/img/branding/raster/favi_unused/profiles.png
  global/img/branding/raster/favi_unused/rankings.png
  global/img/branding/raster/favi_unused/skins.png
  global/img/branding/vector/favi_unused/medals.svg
  global/img/branding/vector/favi_unused/polls.svg
  global/img/branding/vector/favi_unused/profiles.svg
  global/img/branding/vector/favi_unused/rankings.svg
  global/img/branding/vector/favi_unused/skins.svg
  global/js/comment_system.js
  global/lang/en_GB/home.json
  global/php/navbar.php
  home/img-comp/background.png
  home/img-comp/background.svg
  home/img-comp/badges.png
  home/img-comp/eclipse.png
  home/img-comp/faq-bg.png
  home/img-comp/faq.png
  home/img-comp/faqs/snapshots_files.png
  home/img-comp/heart.svg
  home/img-comp/medalhunters-bg.svg
  home/img-comp/medalhunters.svg
  home/img-comp/medals.png
  home/img-comp/newmedals.png
  home/img-comp/orig/eclipse.png
  home/img-comp/orig/medals.png
  home/img-comp/orig/newmedals.png
  home/img-comp/orig/rankings.png
  home/img-comp/osekai.svg
  home/img-comp/pfps/blur/electroyan.jpg
  home/img-comp/pfps/blur/hubz.jpg
  home/img-comp/pfps/blur/iluvskins.jpg
  home/img-comp/pfps/blur/mulraf.png
  home/img-comp/pfps/blur/remyria.jpg
  home/img-comp/pfps/electroyan.jpg
  home/img-comp/pfps/hubz.jpg
  home/img-comp/pfps/iluvskins.jpg
  home/img-comp/pfps/mulraf.png
  home/img-comp/pfps/orig/electroyan.jpg
  home/img-comp/pfps/orig/hubz.jpg
  home/img-comp/pfps/orig/mulraf.png
  home/img-comp/pfps/orig/remyria.jpg
  home/img-comp/pfps/remyria.jpg
  home/img-comp/profiles.png
  home/img-comp/rankings.png
  home/img-comp/snapshots.png
  home/img-comp/support.png
  home/img/harumachi-bg.png
  home/img/harumachi.svg
  home/index.php
  medals/dev.php
  medals/new_ui.php
Labels: size/XXL

#214 Tools update
  tools/css/main.css
  tools/img/bg.jpg
  tools/js/functions.js
Labels: size/S

#218 Fiz azelia migrations
  azelia/database/legacymigration.php
Labels: size/XS

#219 actually remove the old user panel
  index.php
Labels: size/S

#221 Make contant.php use current year instead of hardcoded
  legal/contact.php
Labels: size/XS

#222 Fix report system
  api/sendReport.php
Labels: size/XS

#225 Add note for osekai snapshots review submission stuff
  snapshots/index.php
Labels: size/S

#227 Move tools to database
  db/1.template.sql
  tools/src/medal-name-quiz/README.md
  tools/src/medal-name-quiz/js/functions.js
  tools/src/medal-percentage-calc/README.md
  tools/src/medal-percentage-calc/js/functions.js
  tools/src/pp-calc/README.md
  tools/src/pp-calc/api/recent_scores.php
  tools/src/pp-calc/css/main.css
  tools/src/pp-calc/images/DT.png
  tools/src/pp-calc/images/EZ.png
  tools/src/pp-calc/images/FL.png
  tools/src/pp-calc/images/HD.png
  tools/src/pp-calc/images/HR.png
  tools/src/pp-calc/images/HT.png
  tools/src/pp-calc/index.php
  tools/src/pp-calc/js/functions.js
  tools/src/stdev-pp-calc/README.md
  tools/src/stdev-pp-calc/css/main.css
  tools/src/stdev-pp-calc/index.php
  tools/src/stdev-pp-calc/js/functions.js
  tools/tool.php
  tools/tools.php
Labels: size/M

#229 Fix idiotic mistake in language dropdown
  global/js/navbar.js
Labels: size/XS

#231 add version to navbar js
  global/php/navbar.php
Labels: size/XS

#230 Fix some warnings c:
  global/api/notification_system.php
  home/team.php
Labels: size/S

#228 Add progress and past tasks to osekai rankings
  db/1.template.sql
  global/js/variables.js
  rankings/api/api.php
  rankings/api/upload/scripts-rust/finish.php
  rankings/api/upload/scripts-rust/progression.php
  rankings/index.php
  rankings/js/functions.js
Labels: size/L

#232 Remove experimental status from tasks list rankings
  rankings/index.php
Labels: size/M

#233 Add ?v= to rankings js
  rankings/index.php
Labels: size/XS

#234 Add ETA text to tasks on rankings
  rankings/js/functions.js
Labels: size/XS

#235 Add v key to most js src
  authenticator/auth.php
  azelia/index.php
  badges/index.php
  donate/index.php
  global/js/navbar.js
  global/php/commentsPanel.php
  global/php/functions.php
  global/php/functionsEnd.php
  global/php/medalHoverV2.php
  global/php/navbar.php
  global/php/osekaiReportSystem.php
  global/php/search_overlay.php
  home/index.php
  legal/contact.php
  medals/index.php
  misc/changelog/index.php
  misc/groups/index.php
  profiles/index.php
  rankings/index.php
  snapshots/index.php
  tools/index.php
  tools/src/comparer/index.php
  tools/tool.php
Labels: size/L

#236 Sort roles on homepage and wrap on smaller screens
  db/1.template.sql
  db/3.snippet.rankings.sql
  global/php/functions.php
  home/css/main.css
Labels: Bug, size/XXL, Code, Frontend, changelog:Change

#237 fix comments
  global/php/functions.php
Labels: size/XS

#238 Restore tooltip code
  global/js/main.js
Labels: size/S

#239 Add tooltips to groups
  global/js/localization.js
  global/js/main.js
Labels: size/S

#240 Fix rankings progress finish
  rankings/api/upload/scripts-rust/finish.php
Labels: size/XS

#241 fix htaccess http redirect
  .htaccess
Labels: size/XS

#242 Fix groups dropdown
  global/css/main.css
Labels: Enhancement, size/XS, Code, Design, Frontend, Backend, changelog:Change

#244 Use Int instead of String for tags on changelog
  misc/changelog/api/changelog_update.php
Labels: Code, Backend, changelog:Change

#245 Merge JS files a bit, remove some unused stuff
  404/index.php
  authenticator/auth.php
  azelia/index.php
  badges/index.php
  donate/index.php
  global/js/dropdown_system.js
  global/js/main.js
  global/js/mobileManager.js
  global/js/navbar.js
  global/js/report_system.js
  global/php/functions.php
  global/php/navbar.php
  home/index.php
  home/testLocalization.php
  index.php
  legal/contact.php
  legal/licences.php
  legal/privacy.php
  medals/index.php
  misc/changelog/index.php
  misc/groups/index.php
  misc/translators/index.php
  omh/retro_achiever/index.php
  profiles/index.php
  rankings/index.php
  snapshots/index.php
  tools/index.php
  tools/tool.php
Labels: Code, size/L, changelog:Change
