Repository Osekai/osekai, pull requests merged in 2023-10, with the labels that each got.

#361 osekai at coe
  home/css/light.css
  home/css/main.css
  home/img/coe.png
  home/img/coe.svg
  home/index.php
Labels: size/L

#362 Update teams page
  home/api/team.php
  home/js/main.js
Labels: size/M

#363 Update `Team`
  home/api/team.php
Labels: size/XS

#364 fix search category tooltip & team badge
  global/js/search.js
  home/css/main.css
Labels: size/S
