Repository Osekai/osekai, pull requests merged in 2023-05, with the labels that each got.

#288 Fix background clipping in medals page if too few comments.
  global/css/comments.css
Labels: size/XS

#209 Update Readme
  README.md
Labels: size/M

#290 Fix a bug with database when using Docker
  db/1.template.sql
  docker-compose.yml
Labels: size/XS

#291 fix scripts apis
  rankings/api/upload/scripts-rust/up_ranking.php
Labels: size/S

#292 Add favourite medals table and API
  db/1.template.sql
  global/php/api_controller.php
  global/php/functions.php
  global/php/json_validator.php
  medals/api/favourite.php
Labels: size/L

#293 add bento
  global/lang/en_GB/home.json
  home/api/team.php
Labels: size/S

#294 FUCK
  home/api/team.php
Labels: size/XS

#296 new medals out now!
  home/index.php
Labels: size/L

#297 scuffeder
  global/js/variables.js
Labels: size/XS

#298 FUCK
  global/php/functions.php
Labels: size/XS

#299 medals: Fix medals with & in name not having correct url
  medals/js/functions.js
Labels: size/XS
